/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-07-08 12:37:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class javaBean_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<html>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
      rmg.student student = null;
      synchronized (application) {
        student = (rmg.student) _jspx_page_context.getAttribute("student", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (student == null){
          student = new rmg.student();
          _jspx_page_context.setAttribute("student", student, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      out.print(student.getName());
      out.write("<br>\r\n");
 student.setName("cong"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((rmg.student)_jspx_page_context.findAttribute("student")).getClassNo())));
      out.write(" <br>\r\n");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((rmg.student)_jspx_page_context.findAttribute("student")).getName())));
      out.write(" <br>\r\n");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((rmg.student)_jspx_page_context.findAttribute("student")).getAge())));
      out.write(" <br>\r\n");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((rmg.student)_jspx_page_context.findAttribute("student")).getSexy())));
      out.write(" <br>\r\n");
      out.write('\r');
      out.write('\n');
      out.print(student.getClassNo() );
      out.write(" <br>\r\n");
      out.print(student.getName() );
      out.write(" <br>\r\n");
      out.print(student.getAge() );
      out.write(" <br>\r\n");
      out.print(student.getSexy() );
      out.write(" <br>\r\n");
      out.write('\r');
      out.write('\n');
      java.util.Date date = null;
      synchronized (session) {
        date = (java.util.Date) _jspx_page_context.getAttribute("date", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (date == null){
          date = new java.util.Date();
          _jspx_page_context.setAttribute("date", date, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      out.print(date);
      out.write("<br>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
