/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-07-25 02:19:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DownServlet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table style=\"margin-top:width=\"500\" border=\"1\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\"\r\n");
      out.write("       bordercolor=\"#FFFFFF\" bordercolorligth=\"#FFFFFF\" bordercoloreddark=\"#FFCCCC\">\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("       <tr>\r\n");
      out.write("       \t\t<td width=\"29%\" height=\"27\" align=\"center\">  标题</td>\r\n");
      out.write("       \t\t<td width=\"14%\" height=\"27\" align=\"center\"> 上传人 </td>\r\n");
      out.write("       \t\t<td width=\"23%\" height=\"27\" align=\"center\"> 上传时间</td>\r\n");
      out.write("       \t\t<td width=\"6%\"  height=\"27\" align=\"center\"> 下载</td>\t\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("       <td heigth=\"29\" align=\"center\"> 新歌</td>\r\n");
      out.write("       <td align=\"center\"> 小雨</td>\r\n");
      out.write("       <td align=\"center\">2012年7月24日</td>\r\n");
      out.write("       <td align=\"center\">\r\n");
      out.write("       \r\n");
      out.write("             <a href=\"DownServlet?path=F:\\\\语言\\\\java 有关\\\\jsp\\\\源代码\\\\FileUpload\\\\upload\\\\Sleep Away.mp3\"> 下载</a>\r\n");
      out.write("       </td>\r\n");
      out.write("       </tr>\r\n");
      out.write("   \r\n");
      out.write("</table>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../filecss/1.js\"></script> \r\n");
      out.write("\r\n");
      out.write("<img id = \"obj\" src=\"1 (1).jpg\" border = 0 /> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
